# Start with a base image for Maven
FROM maven:3.8.4-openjdk-17-slim AS build

# Set the working directory in the image
WORKDIR /usr/src/app

# Copy the pom.xml file
COPY ./pom.xml ./pom.xml

# Download all required dependencies into one layer
RUN mvn dependency:go-offline -B

# Copy your other files
COPY ./src ./src

# Build the application
RUN mvn clean install

# Start with a base image containing Java runtime
FROM maven:3.8.4-openjdk-17-slim

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Copy the application's jar file from the build stage image
COPY --from=build /usr/src/app/target/helloworldwincontainer-0.0.1-SNAPSHOT.jar helloworldlincontainer.jar

# Run the jar file 
ENTRYPOINT ["java","-jar","/helloworldlincontainer.jar"]



